import httpx
import os
import time

class RuleMachineAPI:

    def __init__(self, token, api_base_url, ssl_verify=False):
        """
        Token and API URL are generated by Hubitat when making Maker API
        API URL takes the form of 'https://[hub-ip-address-or-hostname]/apps/api/[app-id]'
        """
        self.token = token
        self.api_base_url = api_base_url
        self.ssl_verify = ssl_verify
        
    def _request_sender(self, url_suffix):
        """
        Helper function to send commands to Hubitat Maker API
        """
        params = {'access_token': self.token}
        url = '{}/{}'.format(self.api_base_url, url_suffix)
        return httpx.get(url, params=params, verify=self.ssl_verify)

    def list_rules(self):
        """
        Lists available rules
        """
        r = self._request_sender('getRuleList')
        print(r.headers)
        return r.json()